#![warn(clippy::all, clippy::pedantic)]

use clap::Parser;
use color_eyre::Result;
use crossterm::{
    event::{self, Event, KeyCode, KeyEventKind},
    execute,
    terminal::{disable_raw_mode, enable_raw_mode, EnterAlternateScreen, LeaveAlternateScreen},
};
use ollama_rs::{generation::completion::request::GenerationRequest, Ollama};
use ratatui::{
    backend::CrosstermBackend,
    layout::{Constraint, Direction, Layout},
    style::{Color, Modifier, Style},
    text::{Line, Span},
    widgets::{Block, Borders, List, ListItem, Paragraph},
    Terminal,
};
use std::io;
use std::path::PathBuf;
use tokio_stream::StreamExt;

/// Get the platform-appropriate path for the history file.
/// On macOS: ~/Library/Caches/chat/history
/// On Linux: ~/.cache/chat/history
/// Creates parent directories if they don't exist.
#[allow(dead_code)] // Used by load_history and save_history
fn get_history_path() -> Option<PathBuf> {
    let cache_dir = dirs::cache_dir()?;
    let history_dir = cache_dir.join("chat");

    // Create parent directories if they don't exist
    if !history_dir.exists() {
        std::fs::create_dir_all(&history_dir).ok()?;
    }

    Some(history_dir.join("history"))
}

/// Load history from the cache file.
/// Returns an empty Vec if the file doesn't exist, is empty, or cannot be read.
async fn load_history() -> Vec<String> {
    let Some(path) = get_history_path() else {
        return Vec::new();
    };

    // Read the file contents, returning empty Vec on any error
    let Ok(contents) = tokio::fs::read_to_string(&path).await else {
        return Vec::new();
    };

    // Parse lines, filtering out empty lines
    contents
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .map(String::from)
        .collect()
}

/// Save history to the cache file.
/// Each entry is written on its own line.
/// Silently fails if the file cannot be written (e.g., permission errors).
async fn save_history(history: &[String]) {
    let Some(path) = get_history_path() else {
        return;
    };

    // Join entries with newlines and write to file
    let contents = history.join("\n");
    let _ = tokio::fs::write(&path, contents).await;
}

/// System prompt for generating multiple command options
const MULTI_OPTION_PROMPT: &str = r"You are Chatty, a natural language to zsh shell command translation engine for MacOS.
You are an expert in zsh on MacOS and solve problems by providing shell commands.

Generate 1 to 3 distinct command options that solve the user's problem. Each option should be a different approach or variation.

OUTPUT FORMAT (you MUST follow this exactly):
For each option, output a line starting with the option number, then the command, then a pipe character, then the explanation.
Format: NUMBER. COMMAND | EXPLANATION

Example output:
1. ls -la | Lists all files including hidden ones with detailed information
2. eza -la --icons | Uses eza (modern ls) with icons for better visualization
3. find . -maxdepth 1 -ls | Uses find to list current directory contents with details

RULES:
* Output 1 to 3 options, each on its own line
* Each command must be valid zsh syntax for MacOS
* Each command must solve the user's problem
* Commands should be distinct approaches when possible
* Keep explanations concise (one sentence)
* Do not use markdown formatting or code blocks
* Try to use modern CLI tools when appropriate: jq, bat, eza, fd, fzf, rg, xh

The problem is: ";

/// Model name for the Ollama LLM
const MODEL_NAME: &str = "qwen3-coder:latest";

/// A single command option generated by the LLM
#[derive(Debug, Clone)]
#[allow(dead_code)] // Fields used in US-005 for displaying command list
struct CommandOption {
    /// The shell command
    command: String,
    /// Explanation of what the command does
    explanation: String,
}

/// Current mode/state of the application
#[derive(Default, Clone, Copy, PartialEq, Eq)]
enum AppState {
    /// User is typing their query
    #[default]
    Input,
    /// Waiting for LLM response
    Loading,
    /// Commands have been generated and are ready for selection
    SelectingCommand,
}

/// Application state for the TUI
struct App {
    /// Current input text
    input: String,
    /// Current cursor position in the input
    cursor_position: usize,
    /// Current application state
    state: AppState,
    /// Counter for loading animation (used for spinner)
    loading_tick: usize,
    /// Generated command options from LLM (populated after loading completes)
    generated_options: Vec<CommandOption>,
    /// Currently selected command index (0-based)
    selected_index: usize,
    /// History of previous queries (most recent first)
    history: Vec<String>,
    /// Currently selected history index when dropdown is visible (None = no selection)
    history_index: Option<usize>,
}

impl App {
    /// Create a new App instance, loading history from cache
    async fn new() -> Self {
        let history = load_history().await;
        Self {
            input: String::new(),
            cursor_position: 0,
            state: AppState::default(),
            loading_tick: 0,
            generated_options: Vec::new(),
            selected_index: 0,
            history,
            history_index: None,
        }
    }

    /// Insert a character at the cursor position.
    /// Resets history selection since the filtered list may change.
    fn insert_char(&mut self, c: char) {
        self.input.insert(self.cursor_position, c);
        self.cursor_position += 1;
        self.history_index = None; // Reset selection when input changes
    }

    /// Delete the character before the cursor (backspace).
    /// Resets history selection since the filtered list may change.
    fn delete_char(&mut self) {
        if self.cursor_position > 0 {
            self.cursor_position -= 1;
            self.input.remove(self.cursor_position);
            self.history_index = None; // Reset selection when input changes
        }
    }

    /// Delete the character at the cursor (delete key).
    /// Resets history selection since the filtered list may change.
    fn delete_char_forward(&mut self) {
        if self.cursor_position < self.input.len() {
            self.input.remove(self.cursor_position);
            self.history_index = None; // Reset selection when input changes
        }
    }

    /// Move cursor left
    fn move_cursor_left(&mut self) {
        if self.cursor_position > 0 {
            self.cursor_position -= 1;
        }
    }

    /// Move cursor right
    fn move_cursor_right(&mut self) {
        if self.cursor_position < self.input.len() {
            self.cursor_position += 1;
        }
    }

    /// Move cursor to start of input
    fn move_cursor_home(&mut self) {
        self.cursor_position = 0;
    }

    /// Move cursor to end of input
    fn move_cursor_end(&mut self) {
        self.cursor_position = self.input.len();
    }

    /// Submit the current query and start loading
    /// Returns true if query was submitted, false otherwise
    fn submit_query(&mut self) -> bool {
        if !self.input.trim().is_empty() && self.state == AppState::Input {
            self.state = AppState::Loading;
            self.loading_tick = 0;
            true
        } else {
            false
        }
    }

    /// Increment the loading animation tick
    fn tick_loading(&mut self) {
        if self.state == AppState::Loading {
            self.loading_tick = self.loading_tick.wrapping_add(1);
        }
    }

    /// Get the current spinner character for the loading animation
    fn spinner_char(&self) -> char {
        const SPINNER_CHARS: [char; 4] = ['⠋', '⠙', '⠸', '⠴'];
        SPINNER_CHARS[(self.loading_tick / 2) % SPINNER_CHARS.len()]
    }

    /// Check if input is currently enabled
    fn is_input_enabled(&self) -> bool {
        self.state == AppState::Input
    }

    /// Transition from loading to command selection (called when LLM response arrives)
    fn complete_loading(&mut self) {
        if self.state == AppState::Loading {
            self.state = AppState::SelectingCommand;
            self.selected_index = 0;
        }
    }

    /// Move selection up (with wrap-around: up from first goes to last)
    fn select_previous(&mut self) {
        if !self.generated_options.is_empty() {
            if self.selected_index == 0 {
                self.selected_index = self.generated_options.len() - 1;
            } else {
                self.selected_index -= 1;
            }
        }
    }

    /// Move selection down (with wrap-around: down from last goes to first)
    fn select_next(&mut self) {
        if !self.generated_options.is_empty() {
            self.selected_index = (self.selected_index + 1) % self.generated_options.len();
        }
    }

    /// Confirm the current selection
    /// Returns the selected command if in `SelectingCommand` state with options, None otherwise
    fn confirm_selection(&self) -> Option<&CommandOption> {
        if self.state == AppState::SelectingCommand && !self.generated_options.is_empty() {
            self.generated_options.get(self.selected_index)
        } else {
            None
        }
    }

    /// Regenerate options by re-querying the LLM with the same input
    /// Returns true if regeneration was started, false otherwise
    fn regenerate(&mut self) -> bool {
        if self.state == AppState::SelectingCommand && !self.input.trim().is_empty() {
            self.state = AppState::Loading;
            self.loading_tick = 0;
            self.generated_options.clear();
            true
        } else {
            false
        }
    }

    /// Add a query to history.
    /// - Duplicates are moved to the top (old entry removed)
    /// - History is capped at 10 entries (oldest removed when exceeded)
    fn add_to_history(&mut self, query: &str) {
        let query = query.trim().to_string();
        if query.is_empty() {
            return;
        }

        // Remove duplicate if it exists
        self.history.retain(|h| h != &query);

        // Add to the front (most recent first)
        self.history.insert(0, query);

        // Cap at 10 entries
        self.history.truncate(10);
    }

    /// Move history selection up (selects last if none selected, wraps around).
    /// Uses filtered history for navigation to ensure selection stays within visible items.
    fn select_history_previous(&mut self) {
        let filtered = self.filtered_history();
        if filtered.is_empty() {
            return;
        }
        // Find current position in filtered list
        let current_pos = self
            .history_index
            .and_then(|idx| filtered.iter().position(|(orig_idx, _)| *orig_idx == idx));

        let new_pos = match current_pos {
            // No selection or at first, go to last (wrap around)
            None | Some(0) => filtered.len() - 1,
            Some(pos) => pos - 1,
        };

        // Set history_index to the original index of the selected filtered item
        self.history_index = Some(filtered[new_pos].0);
    }

    /// Move history selection down (selects first if none selected, wraps around).
    /// Uses filtered history for navigation to ensure selection stays within visible items.
    fn select_history_next(&mut self) {
        let filtered = self.filtered_history();
        if filtered.is_empty() {
            return;
        }
        // Find current position in filtered list
        let current_pos = self
            .history_index
            .and_then(|idx| filtered.iter().position(|(orig_idx, _)| *orig_idx == idx));

        let new_pos = match current_pos {
            None => 0, // No selection, go to first
            Some(pos) => (pos + 1) % filtered.len(), // Wrap around
        };

        // Set history_index to the original index of the selected filtered item
        self.history_index = Some(filtered[new_pos].0);
    }

    /// Select the history entry at current index, populate input, and close dropdown
    /// Returns true if selection was made, false otherwise
    fn confirm_history_selection(&mut self) -> bool {
        if let Some(idx) = self.history_index {
            if let Some(entry) = self.history.get(idx).cloned() {
                self.input = entry;
                self.cursor_position = self.input.len();
                self.history_index = None; // Close dropdown
                return true;
            }
        }
        false
    }

    /// Reset history selection (close dropdown without selecting)
    fn reset_history_selection(&mut self) {
        self.history_index = None;
    }

    /// Delete the currently selected history entry.
    /// Returns true if an entry was deleted, false otherwise.
    fn delete_history_entry(&mut self) -> bool {
        if let Some(idx) = self.history_index {
            if idx < self.history.len() {
                self.history.remove(idx);
                return true;
            }
        }
        false
    }

    /// Get the filtered history entries based on current input.
    /// If input is empty, returns all history entries.
    /// Otherwise, filters to entries containing the input text (case-insensitive substring match).
    /// Returns tuples of (`original_index`, entry) to preserve index for selection.
    fn filtered_history(&self) -> Vec<(usize, &String)> {
        if self.input.is_empty() {
            // Return all history entries with their original indices
            self.history.iter().enumerate().collect()
        } else {
            // Filter to entries containing the input text (case-insensitive)
            let input_lower = self.input.to_lowercase();
            self.history
                .iter()
                .enumerate()
                .filter(|(_, entry)| entry.to_lowercase().contains(&input_lower))
                .collect()
        }
    }
}

/// Parse command options from LLM response
/// Expected format: "1. command | explanation" per line
fn parse_command_options(response: &str) -> Vec<CommandOption> {
    let mut options = Vec::new();

    for line in response.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }

        // Try to parse format: "N. command | explanation"
        // First, try to strip the leading number and dot
        let stripped = if let Some(rest) = line
            .strip_prefix("1.")
            .or_else(|| line.strip_prefix("2."))
            .or_else(|| line.strip_prefix("3."))
        {
            rest.trim()
        } else {
            continue; // Skip lines that don't match the expected format
        };

        // Split by pipe to separate command from explanation
        if let Some(pipe_pos) = stripped.find('|') {
            let command = stripped[..pipe_pos].trim().to_string();
            let explanation = stripped[pipe_pos + 1..].trim().to_string();

            // Only add if both command and explanation are non-empty
            if !command.is_empty() && !explanation.is_empty() {
                options.push(CommandOption {
                    command,
                    explanation,
                });
            }
        }
    }

    // Limit to 3 options maximum
    options.truncate(3);
    options
}

/// Generate command options from the LLM
async fn generate_command_options(query: &str) -> Result<Vec<CommandOption>> {
    let ollama = Ollama::default();

    // Build the full prompt
    let prompt = format!("{MULTI_OPTION_PROMPT}{query}");
    let request = GenerationRequest::new(MODEL_NAME.into(), prompt);

    // Stream the response and collect it
    let mut stream = ollama.generate_stream(request).await?;
    let mut response = String::new();

    while let Some(Ok(res)) = stream.next().await {
        for ele in res {
            response += ele.response.as_str();
        }
    }

    // Parse the response into command options
    let options = parse_command_options(&response);

    // If no options were parsed, create a fallback with the raw response
    if options.is_empty() {
        // Try to use the raw response as a single command
        let trimmed = response.trim();
        if !trimmed.is_empty() {
            return Ok(vec![CommandOption {
                command: trimmed.to_string(),
                explanation: "Generated command".to_string(),
            }]);
        }
    }

    Ok(options)
}

#[derive(Parser)]
#[command(version)]
struct Cli {}

#[tokio::main]
async fn main() -> Result<()> {
    color_eyre::install()?;
    let _args = Cli::parse();
    run_tui().await
}

/// Initialize the terminal for TUI mode
fn setup_terminal() -> Result<Terminal<CrosstermBackend<io::Stdout>>> {
    enable_raw_mode()?;
    let mut stdout = io::stdout();
    execute!(stdout, EnterAlternateScreen)?;
    let backend = CrosstermBackend::new(stdout);
    let terminal = Terminal::new(backend)?;
    Ok(terminal)
}

/// Restore the terminal to its original state
fn restore_terminal(terminal: &mut Terminal<CrosstermBackend<io::Stdout>>) -> Result<()> {
    disable_raw_mode()?;
    execute!(terminal.backend_mut(), LeaveAlternateScreen)?;
    terminal.show_cursor()?;
    Ok(())
}

/// Copy command to clipboard using arboard
fn copy_to_clipboard(command: &str) -> Result<(), arboard::Error> {
    let mut clipboard = arboard::Clipboard::new()?;
    clipboard.set_text(command)?;
    Ok(())
}

/// Run the TUI application
async fn run_tui() -> Result<()> {
    let mut terminal = setup_terminal()?;

    let result = run_tui_loop(&mut terminal).await;

    // Always restore terminal, even if there was an error
    restore_terminal(&mut terminal)?;

    // Handle the selected command
    if let Ok(Some(command)) = &result {
        // Try to copy to clipboard
        if copy_to_clipboard(command).is_ok() {
            // Print the command and instructions
            println!("\n\x1b[32m✓\x1b[0m Command copied to clipboard:");
            println!("\x1b[1m{command}\x1b[0m");
            println!("\nPaste with \x1b[33mCmd+V\x1b[0m to use.");
        } else {
            // Clipboard failed, just print the command
            println!("\n\x1b[33m!\x1b[0m Selected command:");
            println!("\x1b[1m{command}\x1b[0m");
            println!("\nCopy and paste to use.");
        }
    }

    result.map(|_| ())
}

/// Render the entire UI based on app state
fn render_ui(app: &App, frame: &mut ratatui::Frame) {
    let chunks = Layout::default()
        .direction(Direction::Vertical)
        .margin(1)
        .constraints([Constraint::Length(3), Constraint::Min(1)])
        .split(frame.area());

    // Render input box
    render_input(app, frame, chunks[0]);

    // Render status/content area based on state
    match app.state {
        AppState::Input => {
            // Check if we should show the history dropdown
            let filtered = app.filtered_history();
            if filtered.is_empty() {
                let help_text =
                    "Type your problem and press Enter to submit. Press Esc or Ctrl+C to quit.";
                let status_block = Block::default()
                    .borders(Borders::ALL)
                    .border_style(Style::default().fg(Color::DarkGray));
                let status = Paragraph::new(help_text)
                    .block(status_block)
                    .style(Style::default().fg(Color::Gray));
                frame.render_widget(status, chunks[1]);
            } else {
                // Split the area: history dropdown (dynamic height) and help text below
                // Filtered history is capped at 10, so this cast is safe
                #[allow(clippy::cast_possible_truncation)]
                let history_height = (filtered.len() as u16).min(10) + 2; // +2 for borders
                let sub_chunks = Layout::default()
                    .direction(Direction::Vertical)
                    .constraints([Constraint::Length(history_height), Constraint::Min(1)])
                    .split(chunks[1]);

                render_history_dropdown(app, &filtered, frame, sub_chunks[0]);

                // Render help text below
                let help_text =
                    "↑/↓ Navigate history  Enter Select  Type to filter. Esc to quit.";
                let status_block = Block::default()
                    .borders(Borders::ALL)
                    .border_style(Style::default().fg(Color::DarkGray));
                let status = Paragraph::new(help_text)
                    .block(status_block)
                    .style(Style::default().fg(Color::Gray));
                frame.render_widget(status, sub_chunks[1]);
            }
        }
        AppState::Loading => {
            render_loading(app, frame, chunks[1]);
        }
        AppState::SelectingCommand => {
            render_command_list(app, frame, chunks[1]);
        }
    }
}

/// Result of handling a key event in the TUI
enum KeyAction {
    /// No special action, continue the loop
    Continue,
    /// Exit the TUI loop
    Exit,
    /// Exit with a selected command
    SelectCommand(String),
    /// Spawn an LLM task with the given query
    SpawnLlmTask(String),
}

/// Handle a key event in the TUI
/// Returns the action to take based on the key pressed
fn handle_key_event(app: &mut App, key: event::KeyEvent) -> KeyAction {
    if key.kind != KeyEventKind::Press {
        return KeyAction::Continue;
    }

    match key.code {
        KeyCode::Esc => {
            // In input state with history dropdown open, close dropdown first
            if app.state == AppState::Input && app.history_index.is_some() {
                app.reset_history_selection();
            } else if app.state == AppState::Input {
                return KeyAction::Exit;
            } else {
                app.state = AppState::Input;
                return KeyAction::Continue; // Signal to abort LLM task if running
            }
        }
        KeyCode::Char('c') if key.modifiers.contains(event::KeyModifiers::CONTROL) => {
            return KeyAction::Exit;
        }
        // History dropdown navigation - only when dropdown is visible
        KeyCode::Up if should_show_history_dropdown(app) => {
            app.select_history_previous();
        }
        KeyCode::Down if should_show_history_dropdown(app) => {
            app.select_history_next();
        }
        // History selection confirmation - when a history entry is selected
        KeyCode::Enter if app.is_input_enabled() && app.history_index.is_some() => {
            app.confirm_history_selection();
        }
        // Input handling - submit query
        KeyCode::Enter if app.is_input_enabled() => {
            if app.submit_query() {
                let query = app.input.clone();
                app.add_to_history(&query);
                return KeyAction::SpawnLlmTask(query);
            }
        }
        // Command selection navigation
        KeyCode::Up if app.state == AppState::SelectingCommand => {
            app.select_previous();
        }
        KeyCode::Down if app.state == AppState::SelectingCommand => {
            app.select_next();
        }
        KeyCode::Enter if app.state == AppState::SelectingCommand => {
            if let Some(selected) = app.confirm_selection() {
                return KeyAction::SelectCommand(selected.command.clone());
            }
        }
        KeyCode::Char('r') if app.state == AppState::SelectingCommand => {
            if app.regenerate() {
                return KeyAction::SpawnLlmTask(app.input.clone());
            }
        }
        KeyCode::Backspace if app.is_input_enabled() => app.delete_char(),
        KeyCode::Delete if app.is_input_enabled() => app.delete_char_forward(),
        KeyCode::Left if app.is_input_enabled() => app.move_cursor_left(),
        KeyCode::Right if app.is_input_enabled() => app.move_cursor_right(),
        KeyCode::Home if app.is_input_enabled() => app.move_cursor_home(),
        KeyCode::End if app.is_input_enabled() => app.move_cursor_end(),
        // Delete history entry - only when dropdown is visible AND entry is selected
        KeyCode::Char('x')
            if app.is_input_enabled()
                && should_show_history_dropdown(app)
                && app.history_index.is_some() =>
        {
            app.delete_history_entry();
        }
        KeyCode::Char(c) if app.is_input_enabled() => app.insert_char(c),
        _ => {}
    }
    KeyAction::Continue
}

/// Main TUI event loop
/// Returns the selected command if one was chosen, None if user cancelled
async fn run_tui_loop(
    terminal: &mut Terminal<CrosstermBackend<io::Stdout>>,
) -> Result<Option<String>> {
    let mut app = App::new().await;

    // Handle for the async LLM generation task
    let mut llm_task: Option<tokio::task::JoinHandle<Result<Vec<CommandOption>>>> = None;

    // Selected command to return
    let mut selected_command: Option<String> = None;

    loop {
        terminal.draw(|frame| render_ui(&app, frame))?;

        // Tick loading animation
        app.tick_loading();

        // Check if LLM task has completed
        if let Some(task) = &mut llm_task {
            if task.is_finished() {
                // Take ownership of the task to await it
                let task = llm_task.take().expect("task should exist");
                match task.await {
                    Ok(Ok(options)) => {
                        app.generated_options = options;
                        app.complete_loading();
                    }
                    Ok(Err(_)) | Err(_) => {
                        // On error, return to input state
                        app.state = AppState::Input;
                    }
                }
            }
        }

        // Handle input events
        if event::poll(std::time::Duration::from_millis(100))? {
            if let Event::Key(key) = event::read()? {
                match handle_key_event(&mut app, key) {
                    KeyAction::Continue => {}
                    KeyAction::Exit => {
                        // Cancel any running LLM task
                        if let Some(task) = llm_task.take() {
                            task.abort();
                        }
                        break;
                    }
                    KeyAction::SelectCommand(cmd) => {
                        selected_command = Some(cmd);
                        break;
                    }
                    KeyAction::SpawnLlmTask(query) => {
                        // Save history asynchronously
                        let history_clone = app.history.clone();
                        tokio::spawn(async move {
                            save_history(&history_clone).await;
                        });
                        // Spawn LLM task
                        llm_task = Some(tokio::spawn(async move {
                            generate_command_options(&query).await
                        }));
                    }
                }
            }
        }
    }

    Ok(selected_command)
}

/// Render the text input widget
fn render_input(app: &App, frame: &mut ratatui::Frame, area: ratatui::layout::Rect) {
    let is_enabled = app.is_input_enabled();

    // Use different border color when disabled
    let border_color = if is_enabled {
        Color::Cyan
    } else {
        Color::DarkGray
    };

    let input_block = Block::default()
        .title(" Describe your problem: ")
        .borders(Borders::ALL)
        .border_style(Style::default().fg(border_color));

    // Build the input text with cursor (only show cursor when enabled)
    let input_text = if is_enabled {
        if app.cursor_position < app.input.len() {
            // Cursor in middle of text
            let before = &app.input[..app.cursor_position];
            let cursor_char = &app.input[app.cursor_position..=app.cursor_position];
            let after = &app.input[app.cursor_position + 1..];

            Line::from(vec![
                Span::raw(before),
                Span::styled(
                    cursor_char,
                    Style::default()
                        .bg(Color::White)
                        .fg(Color::Black)
                        .add_modifier(Modifier::BOLD),
                ),
                Span::raw(after),
            ])
        } else {
            // Cursor at end of text (show block cursor)
            Line::from(vec![
                Span::raw(&app.input),
                Span::styled(
                    " ",
                    Style::default()
                        .bg(Color::White)
                        .fg(Color::Black),
                ),
            ])
        }
    } else {
        // When disabled, just show the text without cursor
        Line::from(app.input.as_str())
    };

    // Use dimmed color when disabled
    let text_color = if is_enabled {
        Color::White
    } else {
        Color::Gray
    };

    let input = Paragraph::new(input_text)
        .block(input_block)
        .style(Style::default().fg(text_color));

    frame.render_widget(input, area);
}

/// Render the loading indicator
fn render_loading(app: &App, frame: &mut ratatui::Frame, area: ratatui::layout::Rect) {
    let loading_block = Block::default()
        .title(" Status ")
        .borders(Borders::ALL)
        .border_style(Style::default().fg(Color::Yellow));

    let spinner = app.spinner_char();
    let loading_text = format!("{spinner} Generating options...");

    let loading = Paragraph::new(loading_text)
        .block(loading_block)
        .style(Style::default().fg(Color::Yellow));

    frame.render_widget(loading, area);
}

/// Render the command options list and explanation pane
fn render_command_list(app: &App, frame: &mut ratatui::Frame, area: ratatui::layout::Rect) {
    // Split the area into three parts: command list (top), hint line, and explanation pane (bottom)
    let chunks = Layout::default()
        .direction(Direction::Vertical)
        .constraints([
            Constraint::Length(5),
            Constraint::Length(1),
            Constraint::Min(3),
        ])
        .split(area);

    // Render command list
    let commands_block = Block::default()
        .title(" Commands ")
        .borders(Borders::ALL)
        .border_style(Style::default().fg(Color::Green));

    // Build list items from generated options
    let items: Vec<ListItem> = app
        .generated_options
        .iter()
        .enumerate()
        .map(|(i, opt)| {
            let is_selected = i == app.selected_index;

            // Format: "N. command"
            let content = format!("{}. {}", i + 1, opt.command);

            // Style based on whether this is the selected item
            let style = if is_selected {
                Style::default()
                    .bg(Color::Cyan)
                    .fg(Color::Black)
                    .add_modifier(Modifier::BOLD)
            } else {
                Style::default().fg(Color::White)
            };

            ListItem::new(Line::from(Span::styled(content, style)))
        })
        .collect();

    // Handle case where there are no options
    if items.is_empty() {
        let no_options = Paragraph::new("No commands generated. Press Esc to try again.")
            .block(commands_block)
            .style(Style::default().fg(Color::Gray));
        frame.render_widget(no_options, chunks[0]);
    } else {
        let list = List::new(items).block(commands_block);
        frame.render_widget(list, chunks[0]);
    }

    // Render hint line with regenerate option
    let hint = Paragraph::new(Line::from(vec![
        Span::styled("↑/↓", Style::default().fg(Color::Yellow)),
        Span::raw(" Navigate  "),
        Span::styled("Enter", Style::default().fg(Color::Yellow)),
        Span::raw(" Select  "),
        Span::styled("r", Style::default().fg(Color::Yellow)),
        Span::raw(" Regenerate  "),
        Span::styled("Esc", Style::default().fg(Color::Yellow)),
        Span::raw(" Cancel"),
    ]));
    frame.render_widget(hint, chunks[1]);

    // Render explanation pane
    render_explanation(app, frame, chunks[2]);
}

/// Check if the history dropdown should be visible.
/// Dropdown is shown when: in Input state and there are matching history entries.
fn should_show_history_dropdown(app: &App) -> bool {
    app.state == AppState::Input && !app.filtered_history().is_empty()
}

/// Render the history dropdown below the input box.
/// Shows filtered history entries, most recent first. Highlights selected entry if any.
fn render_history_dropdown(
    app: &App,
    filtered: &[(usize, &String)],
    frame: &mut ratatui::Frame,
    area: ratatui::layout::Rect,
) {
    let history_block = Block::default()
        .title(" History ")
        .borders(Borders::ALL)
        .border_style(Style::default().fg(Color::DarkGray));

    // Build list items from filtered history
    // The tuple contains (original_index, entry) to preserve selection mapping
    let items: Vec<ListItem> = filtered
        .iter()
        .enumerate()
        .map(|(display_idx, (original_idx, entry))| {
            // Selection is based on original index
            let is_selected = app.history_index == Some(*original_idx);

            // Truncate if too long for display width (account for borders and number prefix)
            let max_width = area.width.saturating_sub(6) as usize; // 2 borders + "N. " prefix
            let display_text = if entry.len() > max_width {
                format!(
                    "{}. {}…",
                    display_idx + 1,
                    &entry[..max_width.saturating_sub(1)]
                )
            } else {
                format!("{}. {}", display_idx + 1, entry)
            };

            // Highlight selected entry with cyan background and bold text
            let style = if is_selected {
                Style::default()
                    .bg(Color::Cyan)
                    .fg(Color::Black)
                    .add_modifier(Modifier::BOLD)
            } else {
                Style::default().fg(Color::Gray)
            };

            ListItem::new(Line::from(Span::styled(display_text, style)))
        })
        .collect();

    let list = List::new(items).block(history_block);
    frame.render_widget(list, area);
}

/// Render the explanation pane for the currently selected command
fn render_explanation(app: &App, frame: &mut ratatui::Frame, area: ratatui::layout::Rect) {
    let explanation_block = Block::default()
        .title(" Explanation: ")
        .borders(Borders::ALL)
        .border_style(Style::default().fg(Color::Magenta));

    // Get the explanation for the currently selected command
    let explanation_text = if app.generated_options.is_empty() {
        String::new()
    } else {
        app.generated_options
            .get(app.selected_index)
            .map_or(String::new(), |opt| opt.explanation.clone())
    };

    let explanation = Paragraph::new(explanation_text)
        .block(explanation_block)
        .style(Style::default().fg(Color::White))
        .wrap(ratatui::widgets::Wrap { trim: true });

    frame.render_widget(explanation, area);
}

