#![warn(clippy::all, clippy::pedantic)]

use clap::{Parser, Subcommand};
use color_eyre::Result;
use crossterm::{
    event::{self, Event, KeyCode, KeyEventKind},
    execute,
    terminal::{disable_raw_mode, enable_raw_mode, EnterAlternateScreen, LeaveAlternateScreen},
};
use ollama_rs::{generation::completion::request::GenerationRequest, Ollama};
use ratatui::{
    backend::CrosstermBackend,
    layout::{Constraint, Direction, Layout},
    style::{Color, Modifier, Style},
    text::{Line, Span},
    widgets::{Block, Borders, List, ListItem, Paragraph},
    Terminal,
};
use std::io;
use tokio::io::{stdout, AsyncWriteExt};
use tokio_stream::StreamExt;

/// System prompt for generating multiple command options
const MULTI_OPTION_PROMPT: &str = r"You are Chatty, a natural language to zsh shell command translation engine for MacOS.
You are an expert in zsh on MacOS and solve problems by providing shell commands.

Generate 1 to 3 distinct command options that solve the user's problem. Each option should be a different approach or variation.

OUTPUT FORMAT (you MUST follow this exactly):
For each option, output a line starting with the option number, then the command, then a pipe character, then the explanation.
Format: NUMBER. COMMAND | EXPLANATION

Example output:
1. ls -la | Lists all files including hidden ones with detailed information
2. eza -la --icons | Uses eza (modern ls) with icons for better visualization
3. find . -maxdepth 1 -ls | Uses find to list current directory contents with details

RULES:
* Output 1 to 3 options, each on its own line
* Each command must be valid zsh syntax for MacOS
* Each command must solve the user's problem
* Commands should be distinct approaches when possible
* Keep explanations concise (one sentence)
* Do not use markdown formatting or code blocks
* Try to use modern CLI tools when appropriate: jq, bat, eza, fd, fzf, rg, xh

The problem is: ";

/// Model name for the Ollama LLM
const MODEL_NAME: &str = "qwen3-coder:latest";

/// A single command option generated by the LLM
#[derive(Debug, Clone)]
#[allow(dead_code)] // Fields used in US-005 for displaying command list
struct CommandOption {
    /// The shell command
    command: String,
    /// Explanation of what the command does
    explanation: String,
}

/// Current mode/state of the application
#[derive(Default, Clone, Copy, PartialEq, Eq)]
enum AppState {
    /// User is typing their query
    #[default]
    Input,
    /// Waiting for LLM response
    Loading,
    /// Commands have been generated and are ready for selection
    SelectingCommand,
}

/// Application state for the TUI
#[derive(Default)]
struct App {
    /// Current input text
    input: String,
    /// Current cursor position in the input
    cursor_position: usize,
    /// Current application state
    state: AppState,
    /// Counter for loading animation (used for spinner)
    loading_tick: usize,
    /// Generated command options from LLM (populated after loading completes)
    generated_options: Vec<CommandOption>,
    /// Currently selected command index (0-based)
    selected_index: usize,
}

impl App {
    /// Insert a character at the cursor position
    fn insert_char(&mut self, c: char) {
        self.input.insert(self.cursor_position, c);
        self.cursor_position += 1;
    }

    /// Delete the character before the cursor (backspace)
    fn delete_char(&mut self) {
        if self.cursor_position > 0 {
            self.cursor_position -= 1;
            self.input.remove(self.cursor_position);
        }
    }

    /// Delete the character at the cursor (delete key)
    fn delete_char_forward(&mut self) {
        if self.cursor_position < self.input.len() {
            self.input.remove(self.cursor_position);
        }
    }

    /// Move cursor left
    fn move_cursor_left(&mut self) {
        if self.cursor_position > 0 {
            self.cursor_position -= 1;
        }
    }

    /// Move cursor right
    fn move_cursor_right(&mut self) {
        if self.cursor_position < self.input.len() {
            self.cursor_position += 1;
        }
    }

    /// Move cursor to start of input
    fn move_cursor_home(&mut self) {
        self.cursor_position = 0;
    }

    /// Move cursor to end of input
    fn move_cursor_end(&mut self) {
        self.cursor_position = self.input.len();
    }

    /// Submit the current query and start loading
    /// Returns true if query was submitted, false otherwise
    fn submit_query(&mut self) -> bool {
        if !self.input.trim().is_empty() && self.state == AppState::Input {
            self.state = AppState::Loading;
            self.loading_tick = 0;
            true
        } else {
            false
        }
    }

    /// Increment the loading animation tick
    fn tick_loading(&mut self) {
        if self.state == AppState::Loading {
            self.loading_tick = self.loading_tick.wrapping_add(1);
        }
    }

    /// Get the current spinner character for the loading animation
    fn spinner_char(&self) -> char {
        const SPINNER_CHARS: [char; 4] = ['⠋', '⠙', '⠸', '⠴'];
        SPINNER_CHARS[(self.loading_tick / 2) % SPINNER_CHARS.len()]
    }

    /// Check if input is currently enabled
    fn is_input_enabled(&self) -> bool {
        self.state == AppState::Input
    }

    /// Transition from loading to command selection (called when LLM response arrives)
    fn complete_loading(&mut self) {
        if self.state == AppState::Loading {
            self.state = AppState::SelectingCommand;
            self.selected_index = 0;
        }
    }

    /// Move selection up (with wrap-around: up from first goes to last)
    fn select_previous(&mut self) {
        if !self.generated_options.is_empty() {
            if self.selected_index == 0 {
                self.selected_index = self.generated_options.len() - 1;
            } else {
                self.selected_index -= 1;
            }
        }
    }

    /// Move selection down (with wrap-around: down from last goes to first)
    fn select_next(&mut self) {
        if !self.generated_options.is_empty() {
            self.selected_index = (self.selected_index + 1) % self.generated_options.len();
        }
    }

    /// Confirm the current selection
    /// Returns the selected command if in `SelectingCommand` state with options, None otherwise
    fn confirm_selection(&self) -> Option<&CommandOption> {
        if self.state == AppState::SelectingCommand && !self.generated_options.is_empty() {
            self.generated_options.get(self.selected_index)
        } else {
            None
        }
    }
}

/// Parse command options from LLM response
/// Expected format: "1. command | explanation" per line
fn parse_command_options(response: &str) -> Vec<CommandOption> {
    let mut options = Vec::new();

    for line in response.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }

        // Try to parse format: "N. command | explanation"
        // First, try to strip the leading number and dot
        let stripped = if let Some(rest) = line
            .strip_prefix("1.")
            .or_else(|| line.strip_prefix("2."))
            .or_else(|| line.strip_prefix("3."))
        {
            rest.trim()
        } else {
            continue; // Skip lines that don't match the expected format
        };

        // Split by pipe to separate command from explanation
        if let Some(pipe_pos) = stripped.find('|') {
            let command = stripped[..pipe_pos].trim().to_string();
            let explanation = stripped[pipe_pos + 1..].trim().to_string();

            // Only add if both command and explanation are non-empty
            if !command.is_empty() && !explanation.is_empty() {
                options.push(CommandOption {
                    command,
                    explanation,
                });
            }
        }
    }

    // Limit to 3 options maximum
    options.truncate(3);
    options
}

/// Generate command options from the LLM
async fn generate_command_options(query: &str) -> Result<Vec<CommandOption>> {
    let ollama = Ollama::default();

    // Build the full prompt
    let prompt = format!("{MULTI_OPTION_PROMPT}{query}");
    let request = GenerationRequest::new(MODEL_NAME.into(), prompt);

    // Stream the response and collect it
    let mut stream = ollama.generate_stream(request).await?;
    let mut response = String::new();

    while let Some(Ok(res)) = stream.next().await {
        for ele in res {
            response += ele.response.as_str();
        }
    }

    // Parse the response into command options
    let options = parse_command_options(&response);

    // If no options were parsed, create a fallback with the raw response
    if options.is_empty() {
        // Try to use the raw response as a single command
        let trimmed = response.trim();
        if !trimmed.is_empty() {
            return Ok(vec![CommandOption {
                command: trimmed.to_string(),
                explanation: "Generated command".to_string(),
            }]);
        }
    }

    Ok(options)
}

#[derive(Parser)]
#[command(version)]
struct Cli {
    #[command(subcommand)]
    cmd: Option<Cmd>,
}
impl Cli {
    fn cmd(&self) -> Cmd {
        self.cmd.clone().unwrap_or(Cmd::Tui)
    }
}

#[derive(Subcommand, Debug, Clone)]
enum Cmd {
    /// Run the application interactively (default)
    Run,
    /// Run the TUI interface
    Tui,
}

#[tokio::main]
async fn main() -> Result<()> {
    color_eyre::install()?;
    let args = Cli::parse();
    match args.cmd() {
        Cmd::Run => run().await,
        Cmd::Tui => run_tui().await,
    }
}

/// Initialize the terminal for TUI mode
fn setup_terminal() -> Result<Terminal<CrosstermBackend<io::Stdout>>> {
    enable_raw_mode()?;
    let mut stdout = io::stdout();
    execute!(stdout, EnterAlternateScreen)?;
    let backend = CrosstermBackend::new(stdout);
    let terminal = Terminal::new(backend)?;
    Ok(terminal)
}

/// Restore the terminal to its original state
fn restore_terminal(terminal: &mut Terminal<CrosstermBackend<io::Stdout>>) -> Result<()> {
    disable_raw_mode()?;
    execute!(terminal.backend_mut(), LeaveAlternateScreen)?;
    terminal.show_cursor()?;
    Ok(())
}

/// Run the TUI application
async fn run_tui() -> Result<()> {
    let mut terminal = setup_terminal()?;

    let result = run_tui_loop(&mut terminal).await;

    // Always restore terminal, even if there was an error
    restore_terminal(&mut terminal)?;

    result
}

/// Render the entire UI based on app state
fn render_ui(app: &App, frame: &mut ratatui::Frame) {
    let chunks = Layout::default()
        .direction(Direction::Vertical)
        .margin(1)
        .constraints([Constraint::Length(3), Constraint::Min(1)])
        .split(frame.area());

    // Render input box
    render_input(app, frame, chunks[0]);

    // Render status/content area based on state
    match app.state {
        AppState::Input => {
            let help_text =
                "Type your problem and press Enter to submit. Press Esc or Ctrl+C to quit.";
            let status_block = Block::default()
                .borders(Borders::ALL)
                .border_style(Style::default().fg(Color::DarkGray));
            let status = Paragraph::new(help_text)
                .block(status_block)
                .style(Style::default().fg(Color::Gray));
            frame.render_widget(status, chunks[1]);
        }
        AppState::Loading => {
            render_loading(app, frame, chunks[1]);
        }
        AppState::SelectingCommand => {
            render_command_list(app, frame, chunks[1]);
        }
    }
}

/// Main TUI event loop
async fn run_tui_loop(terminal: &mut Terminal<CrosstermBackend<io::Stdout>>) -> Result<()> {
    let mut app = App::default();

    // Handle for the async LLM generation task
    let mut llm_task: Option<tokio::task::JoinHandle<Result<Vec<CommandOption>>>> = None;

    loop {
        terminal.draw(|frame| render_ui(&app, frame))?;

        // Tick loading animation
        app.tick_loading();

        // Check if LLM task has completed
        if let Some(task) = &mut llm_task {
            if task.is_finished() {
                // Take ownership of the task to await it
                let task = llm_task.take().expect("task should exist");
                match task.await {
                    Ok(Ok(options)) => {
                        app.generated_options = options;
                        app.complete_loading();
                    }
                    Ok(Err(_)) | Err(_) => {
                        // On error, return to input state
                        app.state = AppState::Input;
                    }
                }
            }
        }

        // Handle input events
        if event::poll(std::time::Duration::from_millis(100))? {
            if let Event::Key(key) = event::read()? {
                if key.kind == KeyEventKind::Press {
                    match key.code {
                        KeyCode::Esc => {
                            // In input state, Esc exits; otherwise, Esc returns to input
                            if app.state == AppState::Input {
                                break;
                            }
                            // Cancel any running LLM task
                            if let Some(task) = llm_task.take() {
                                task.abort();
                            }
                            app.state = AppState::Input;
                        }
                        KeyCode::Char('c')
                            if key.modifiers.contains(event::KeyModifiers::CONTROL) =>
                        {
                            // Cancel any running LLM task
                            if let Some(task) = llm_task.take() {
                                task.abort();
                            }
                            break;
                        }
                        // Input handling - only when input is enabled
                        KeyCode::Enter if app.is_input_enabled() => {
                            if app.submit_query() {
                                // Spawn async LLM task
                                let query = app.input.clone();
                                llm_task = Some(tokio::spawn(async move {
                                    generate_command_options(&query).await
                                }));
                            }
                        }
                        // Command selection navigation
                        KeyCode::Up if app.state == AppState::SelectingCommand => {
                            app.select_previous();
                        }
                        KeyCode::Down if app.state == AppState::SelectingCommand => {
                            app.select_next();
                        }
                        KeyCode::Enter if app.state == AppState::SelectingCommand => {
                            // Confirm selection - for now, just print selected and exit
                            if let Some(selected) = app.confirm_selection() {
                                // Store the command for later use (US-009 will handle pasting)
                                let _selected_command = selected.command.clone();
                                break;
                            }
                        }
                        KeyCode::Backspace if app.is_input_enabled() => app.delete_char(),
                        KeyCode::Delete if app.is_input_enabled() => app.delete_char_forward(),
                        KeyCode::Left if app.is_input_enabled() => app.move_cursor_left(),
                        KeyCode::Right if app.is_input_enabled() => app.move_cursor_right(),
                        KeyCode::Home if app.is_input_enabled() => app.move_cursor_home(),
                        KeyCode::End if app.is_input_enabled() => app.move_cursor_end(),
                        KeyCode::Char(c) if app.is_input_enabled() => app.insert_char(c),
                        _ => {}
                    }
                }
            }
        }
    }

    Ok(())
}

/// Render the text input widget
fn render_input(app: &App, frame: &mut ratatui::Frame, area: ratatui::layout::Rect) {
    let is_enabled = app.is_input_enabled();

    // Use different border color when disabled
    let border_color = if is_enabled {
        Color::Cyan
    } else {
        Color::DarkGray
    };

    let input_block = Block::default()
        .title(" Describe your problem: ")
        .borders(Borders::ALL)
        .border_style(Style::default().fg(border_color));

    // Build the input text with cursor (only show cursor when enabled)
    let input_text = if is_enabled {
        if app.cursor_position < app.input.len() {
            // Cursor in middle of text
            let before = &app.input[..app.cursor_position];
            let cursor_char = &app.input[app.cursor_position..=app.cursor_position];
            let after = &app.input[app.cursor_position + 1..];

            Line::from(vec![
                Span::raw(before),
                Span::styled(
                    cursor_char,
                    Style::default()
                        .bg(Color::White)
                        .fg(Color::Black)
                        .add_modifier(Modifier::BOLD),
                ),
                Span::raw(after),
            ])
        } else {
            // Cursor at end of text (show block cursor)
            Line::from(vec![
                Span::raw(&app.input),
                Span::styled(
                    " ",
                    Style::default()
                        .bg(Color::White)
                        .fg(Color::Black),
                ),
            ])
        }
    } else {
        // When disabled, just show the text without cursor
        Line::from(app.input.as_str())
    };

    // Use dimmed color when disabled
    let text_color = if is_enabled {
        Color::White
    } else {
        Color::Gray
    };

    let input = Paragraph::new(input_text)
        .block(input_block)
        .style(Style::default().fg(text_color));

    frame.render_widget(input, area);
}

/// Render the loading indicator
fn render_loading(app: &App, frame: &mut ratatui::Frame, area: ratatui::layout::Rect) {
    let loading_block = Block::default()
        .title(" Status ")
        .borders(Borders::ALL)
        .border_style(Style::default().fg(Color::Yellow));

    let spinner = app.spinner_char();
    let loading_text = format!("{spinner} Generating options...");

    let loading = Paragraph::new(loading_text)
        .block(loading_block)
        .style(Style::default().fg(Color::Yellow));

    frame.render_widget(loading, area);
}

/// Render the command options list and explanation pane
fn render_command_list(app: &App, frame: &mut ratatui::Frame, area: ratatui::layout::Rect) {
    // Split the area into two parts: command list (top) and explanation pane (bottom)
    let chunks = Layout::default()
        .direction(Direction::Vertical)
        .constraints([Constraint::Length(5), Constraint::Min(3)])
        .split(area);

    // Render command list
    let commands_block = Block::default()
        .title(" Commands ")
        .borders(Borders::ALL)
        .border_style(Style::default().fg(Color::Green));

    // Build list items from generated options
    let items: Vec<ListItem> = app
        .generated_options
        .iter()
        .enumerate()
        .map(|(i, opt)| {
            let is_selected = i == app.selected_index;

            // Format: "N. command"
            let content = format!("{}. {}", i + 1, opt.command);

            // Style based on whether this is the selected item
            let style = if is_selected {
                Style::default()
                    .bg(Color::Cyan)
                    .fg(Color::Black)
                    .add_modifier(Modifier::BOLD)
            } else {
                Style::default().fg(Color::White)
            };

            ListItem::new(Line::from(Span::styled(content, style)))
        })
        .collect();

    // Handle case where there are no options
    if items.is_empty() {
        let no_options = Paragraph::new("No commands generated. Press Esc to try again.")
            .block(commands_block)
            .style(Style::default().fg(Color::Gray));
        frame.render_widget(no_options, chunks[0]);
    } else {
        let list = List::new(items).block(commands_block);
        frame.render_widget(list, chunks[0]);
    }

    // Render explanation pane
    render_explanation(app, frame, chunks[1]);
}

/// Render the explanation pane for the currently selected command
fn render_explanation(app: &App, frame: &mut ratatui::Frame, area: ratatui::layout::Rect) {
    let explanation_block = Block::default()
        .title(" Explanation: ")
        .borders(Borders::ALL)
        .border_style(Style::default().fg(Color::Magenta));

    // Get the explanation for the currently selected command
    let explanation_text = if app.generated_options.is_empty() {
        String::new()
    } else {
        app.generated_options
            .get(app.selected_index)
            .map_or(String::new(), |opt| opt.explanation.clone())
    };

    let explanation = Paragraph::new(explanation_text)
        .block(explanation_block)
        .style(Style::default().fg(Color::White))
        .wrap(ratatui::widgets::Wrap { trim: true });

    frame.render_widget(explanation, area);
}

async fn run() -> Result<()> {
    let prompt = r"
 Your are Chatty, a natural language to zsh shell command translation engine for MacOS.
 You are an expert in zsh on MacOs and solve the problem at the end of the prompt with a zsh command.

 Obey the following rules to generate the correct zsh command:
 * Your output is a single zsh command, you may pipe commands together.
 * The zsh command must solve the question.
 * Be consice and show just the final command in plain text.
 * Only show a single answer.
 * Do not create invalid syntax or cause syntax errors.
 * Remove any explanation or comments.
 * Do not surround the command with any additional characters like quotes or ```.
 * The answer must work on MacOS.
 * The answer must work on zsh.
 * Try to use the following additional commands: jq, bat, eza, fd, fzf, rg, xh

The problem is: \
".to_string();

    let model_name = "qwen3-coder:latest";

    let ollama = Ollama::default();

    let mut stdout = stdout();

    let _ = ollama
        .show_model_info(model_name.to_string())
        .await
        .expect("Failed to get model info, is Ollama server running?");

    stdout
        .write_all(format!("Running model {model_name}\n").as_bytes())
        .await?;
    stdout.flush().await?;

    loop {
        stdout.write_all(b"\n> ").await?;
        stdout.flush().await?;

        let mut input = String::new();
        std::io::stdin().read_line(&mut input)?;

        let input = input.trim_end();
        if input.eq_ignore_ascii_case("exit") {
            break;
        }

        let prompt = prompt.clone() + input;

        let request = GenerationRequest::new(model_name.into(), prompt);

        let mut stream = ollama.generate_stream(request).await?;

        let mut solution = String::new();
        while let Some(Ok(res)) = stream.next().await {
            for ele in res {
                solution += ele.response.as_str();
            }
        }
        println!("{solution}");
    }

    Ok(())
}
